-- GlobeTip 2026 Supabase schema
create extension if not exists pgcrypto;
create table public.profiles (id uuid primary key references auth.users(id) on delete cascade, username text unique, avatar_url text, created_at timestamptz default now());
create table public.stadiums (id text primary key, name text not null, tournament_name text, city text, country text, opened int, capacity int, image_url text, description text, facts jsonb default '[]');
create table public.matches (id text primary key, stage text not null, group_name text, kickoff timestamptz not null, home_team text, away_team text, home_flag text, away_flag text, stadium_id text references public.stadiums(id), status text default 'scheduled', home_score int, away_score int);
create table public.tips (id uuid primary key default gen_random_uuid(), user_id uuid references auth.users(id) on delete cascade, match_id text references public.matches(id) on delete cascade, home_tip int not null check(home_tip>=0), away_tip int not null check(away_tip>=0), points int default 0, created_at timestamptz default now(), updated_at timestamptz default now(), unique(user_id, match_id));
create table public.friendships (id uuid primary key default gen_random_uuid(), requester uuid references auth.users(id) on delete cascade, addressee uuid references auth.users(id) on delete cascade, status text default 'pending', created_at timestamptz default now(), unique(requester, addressee));
alter table public.profiles enable row level security; alter table public.tips enable row level security; alter table public.friendships enable row level security; alter table public.matches enable row level security; alter table public.stadiums enable row level security;
create policy "public read matches" on public.matches for select using (true); create policy "public read stadiums" on public.stadiums for select using (true);
create policy "read own profile" on public.profiles for select using (true); create policy "update own profile" on public.profiles for update using (auth.uid() = id); create policy "insert own profile" on public.profiles for insert with check (auth.uid() = id);
create policy "read own tips" on public.tips for select using (auth.uid() = user_id); create policy "upsert own tips" on public.tips for insert with check (auth.uid() = user_id); create policy "update own tips" on public.tips for update using (auth.uid() = user_id);
create or replace function public.calculate_tip_points(t_home int,t_away int,r_home int,r_away int) returns int language sql immutable as $$ select case when t_home=r_home and t_away=r_away then 3 when sign(t_home-t_away)=sign(r_home-r_away) then 1 else 0 end $$;
create or replace view public.global_leaderboard as select p.id,p.username,coalesce(sum(t.points),0) as points,count(t.id) as tips_count from public.profiles p left join public.tips t on t.user_id=p.id group by p.id,p.username order by points desc;
