const $ = s => document.querySelector(s);
const app = $('#app');
const state = JSON.parse(localStorage.getItem('wc-tip-state') || '{}');
state.user ??= { name:'Frank G', email:'frank@example.com', points:1250, bonus:0, tips:0, discovered:[] };
state.tips ??= {};
save();
function save(){ localStorage.setItem('wc-tip-state', JSON.stringify(state)); }
function toast(msg){ const t=$('#toast'); t.textContent=msg; t.classList.add('show'); setTimeout(()=>t.classList.remove('show'),2600); }
function setView(view){ document.querySelectorAll('.bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===view)); views[view](); window.scrollTo({top:0,behavior:'smooth'}); }
function layout(title, html){ app.innerHTML = `<section><h2>${title}</h2>${html}</section>`; }
const views={
 home(){
  app.innerHTML=`<section class="hero"><div class="brand"><span class="cup">🏆</span><span>WORLD SOCCER<br><b>2026</b></span></div><h1>TIP. <span class="play">PLAY.</span> <span class="win">WIN.</span></h1><p>Tippe Spiele, entdecke Gastgeberländer, sammle Bonuspunkte und klettere in der Rangliste.</p><div class="cta-row"><button class="btn" onclick="setView('games')">JETZT TIPPEN</button><button class="btn secondary" onclick="setView('map')">WELTKARTE</button></div></section><div class="card stats"><div class="stat"><b>${state.user.tips}</b><span>Tipps</span></div><div class="stat"><b>${state.user.points}</b><span>Punkte</span></div><div class="stat"><b>${state.user.bonus}</b><span>Bonus</span></div></div><div class="card"><h3>So funktioniert's</h3><p>1 Punkt für Teilnahme, 5 Punkte für richtige Tendenz, 10 Punkte für exaktes Resultat. Stadion-Discovery bringt Bonuspunkte.</p></div>`;
 },
 games(){
  layout('Spiele', `<div class="tabs"><button class="tab active">Alle Spiele</button><button class="tab">Meine Tipps</button><button class="tab">Gruppenphase</button></div>${WC_DATA.games.map(g=>`<div class="game" onclick="openTip(${g.id})"><div><div class="team">${g.home}</div><div class="small">${g.homeName}</div></div><div class="time"><b>${g.time}</b><span>${g.date}<br>${g.group}</span><div class="small">${state.tips[g.id]?'TIPP GESPEICHERT':'TIPPEN ›'}</div></div><div style="text-align:right"><div class="team">${g.away}</div><div class="small">${g.awayName}</div></div></div>`).join('')}`)
 },
 map(){
  layout('Entdecke die Gastgeber', `<div class="map"><div class="continent"></div>${WC_DATA.countries.map(c=>`<button class="pin" style="left:${c.x}%;top:${c.y}%;background:${c.color}" onclick="openCountry('${c.id}')">${c.name}<span>${c.stadiums} Stadien</span></button>`).join('')}</div><div class="card"><b>Bonuspunktestand ⭐ ${state.user.bonus}</b><p>Klicke auf ein Land und entdecke die Stadien. Jedes entdeckte Stadion bringt Punkte.</p></div>`)
 },
 ranking(){
  const list=[...WC_DATA.ranking];
  layout('Rangliste', `<div class="card" style="background:linear-gradient(135deg,rgba(255,200,61,.32),rgba(8,22,39,.95))"><div class="small">Dein Rang</div><h1 style="margin:8px 0">6</h1><b>${state.user.points + state.user.bonus} Punkte 🏆</b></div>${list.map((r,i)=>`<div class="rank ${r[0]==='Frank G'?'me':''}"><span><b>${i+1}</b> ${r[0]==='Frank G'?'Du':r[0]}</span><b>${r[0]==='Frank G'?state.user.points + state.user.bonus:r[1]}</b></div>`).join('')}`)
 },
 profile(){
  layout('Profil', `<div class="card" style="text-align:center"><button class="avatar" style="width:88px;height:88px;font-size:28px">FG</button><h2>${state.user.name}</h2><p>${state.user.email}</p><div class="stats"><div class="stat"><b>${state.user.tips}</b><span>Tipps</span></div><div class="stat"><b>${state.user.points}</b><span>Punkte</span></div><div class="stat"><b>${state.user.bonus}</b><span>Bonus</span></div></div></div><div class="card form"><h3>Demo Login / Registrierung</h3><input id="name" value="${state.user.name}" placeholder="Name"><input id="email" value="${state.user.email}" placeholder="E-Mail"><button class="btn" onclick="saveProfile()">PROFIL SPEICHERN</button></div><div class="card"><button class="btn secondary" onclick="showMailPreview()">Mail-Vorschau ansehen</button></div>`)
 }
};
function openTip(id){ const g=WC_DATA.games.find(x=>x.id===id); const tip=state.tips[id]||{h:2,a:1,w:'1',goals:'over',both:'yes'}; app.innerHTML=`<section><button class="btn secondary" onclick="setView('games')">‹ Zurück</button><div class="card" style="text-align:center"><h2>${g.home} <span class="small">VS</span> ${g.away}</h2><p>${g.date} · ${g.time}<br>${g.group}</p><h3>Mein Tipp</h3><div class="tipbox"><input class="score" id="homeScore" type="number" min="0" value="${tip.h}"><b>:</b><input class="score" id="awayScore" type="number" min="0" value="${tip.a}"></div><h3>Zusätzliche Tipps</h3><p class="small">Tipp 1X2</p><div class="option-row" data-pick="w"><button class="option ${tip.w==='1'?'active':''}" data-v="1">1</button><button class="option ${tip.w==='X'?'active':''}" data-v="X">X</button><button class="option ${tip.w==='2'?'active':''}" data-v="2">2</button></div><p class="small">Über / Unter 2.5 Tore</p><div class="option-row two" data-pick="goals"><button class="option ${tip.goals==='over'?'active':''}" data-v="over">Über</button><button class="option ${tip.goals==='under'?'active':''}" data-v="under">Unter</button></div><p class="small">Beide Teams treffen</p><div class="option-row two" data-pick="both"><button class="option ${tip.both==='yes'?'active':''}" data-v="yes">Ja</button><button class="option ${tip.both==='no'?'active':''}" data-v="no">Nein</button></div><button class="btn" style="width:100%;margin-top:18px" onclick="saveTip(${id})">TIPP SPEICHERN</button></div></section>`; bindOptions(); }
function bindOptions(){ document.querySelectorAll('.option-row').forEach(row=>row.onclick=e=>{ if(!e.target.matches('.option'))return; row.querySelectorAll('.option').forEach(b=>b.classList.remove('active')); e.target.classList.add('active'); }); }
function getPick(name){ return document.querySelector(`[data-pick="${name}"] .active`)?.dataset.v; }
function saveTip(id){ const existed=!!state.tips[id]; state.tips[id]={h:+$('#homeScore').value,a:+$('#awayScore').value,w:getPick('w'),goals:getPick('goals'),both:getPick('both')}; if(!existed){state.user.tips++; state.user.points+=1;} save(); toast('Tipp gespeichert. Demo-Mail wurde vorbereitet.'); setView('games'); }
function openCountry(id){ const c=WC_DATA.countries.find(x=>x.id===id); const stadiums=WC_DATA.stadiums.filter(s=>s.country===id); app.innerHTML=`<section><button class="btn secondary" onclick="setView('map')">‹ Weltkarte</button><div class="card"><h2>${c.flag} ${c.name}</h2><p>${c.text}</p></div><div class="stadium-grid">${stadiums.map(s=>`<div class="card stadium-card"><img class="stadium-img" src="${s.img}"><h3>${s.name}</h3><p>${s.city}</p><div class="meta"><div class="stat"><b>${s.opened}</b><span>Eröffnet</span></div><div class="stat"><b>${s.capacity}</b><span>Kapazität</span></div><div class="stat"><b>${s.games}</b><span>Spiele</span></div></div><button class="btn" onclick="discover('${s.id}')">ENTDECKEN +${s.bonus} ⭐</button></div>`).join('')}</div></section>`; }
function discover(id){ const s=WC_DATA.stadiums.find(x=>x.id===id); if(state.user.discovered.includes(id)){toast('Dieses Stadion hast du schon entdeckt.');return;} state.user.discovered.push(id); state.user.bonus += s.bonus; save(); toast(`${s.name} entdeckt: +${s.bonus} Bonuspunkte!`); }
function saveProfile(){ state.user.name=$('#name').value||'Frank G'; state.user.email=$('#email').value||'frank@example.com'; save(); toast('Profil gespeichert.'); setView('profile'); }
function showMailPreview(){ const body=`<div class="modal" onclick="this.remove()"><div class="card" onclick="event.stopPropagation()"><h2>Demo Mail</h2><div class="mail-preview"><h2>Dein aktueller Tippstand</h2><p>Hallo ${state.user.name},</p><p>du hast aktuell <b>${state.user.points + state.user.bonus} Punkte</b>, davon <b>${state.user.bonus} Bonuspunkte</b> durch Stadion-Discovery.</p><p>Gespeicherte Tipps: <b>${state.user.tips}</b></p><p>Viel Glück beim nächsten Spiel! ⚽</p></div><button class="btn" style="width:100%;margin-top:14px" onclick="document.querySelector('.modal').remove()">Schließen</button></div></div>`; document.body.insertAdjacentHTML('beforeend',body); }
document.querySelectorAll('.bottom-nav button').forEach(b=>b.onclick=()=>setView(b.dataset.view));
$('#profileBtn').onclick=()=>setView('profile'); $('#menuBtn').onclick=()=>toast('Demo-Menü: API, Mailjet und Supabase können später aktiviert werden.');
setView('home');
